import { diceRandomizer } from "../diceRandomizer.js"
import { armors } from "./armor.js"
import { arms } from "./arms.js"
import { spalls } from "./spalls.js"

export const potions = {

    healingPotion: {name: "Зелье лечения", class: "Зелье характеристик", effect: diceRandomizer(4, 2) + 2, target: "hits", price: 25},
    bhealingPotion: {name: "Большое зелье лечения", class: "Зелье характеристик", effect: diceRandomizer(4, 4) + 4, target: "hits", price: 50},
    ehealingPotion: {name: "Отличное зелье лечения", class: "Зелье характеристик", effect: diceRandomizer(8, 4) + 8, target: "hits", price: 250},
    phealingPotion: {name: "Превосходное зелье лечения", class: "Зелье характеристик", effect: diceRandomizer(10, 4) + 20, target: "hits", price: 2500},

    temporaryHealingPotion: {name: "Зелье временного здоровья", class: "Зелье характеристик", effect: diceRandomizer(4, 2) + 2, target: "time_hits", price: 50},
    btemporaryHealingPotion: {name: "Большое зелье временного здоровья", class: "Зелье характеристик", effect: diceRandomizer(4, 4) + 4, target: "time_hits", price: 100},
    etemporaryHealingPotion: {name: "Отличное зелье временного здоровья", class: "Зелье характеристик", effect: diceRandomizer(8, 4) + 8, target: "time_hits", price: 500},
    ptemporaryHealingPotion: {name: "Превосходное зелье временного здоровья", class: "Зелье характеристик", effect: diceRandomizer(10, 4) + 20, target: "time_hits", price: 5000},

    protectionPotion: {name: "Зелье защиты", class: "Зелье характеристик", effect: 2, target: "ac", price: 75},
    bprotectionPotion: {name: "Большое зелье защиты", class: "Зелье характеристик", effect: 4, target: "ac", price: 150},
    eprotectionPotion: {name: "Отличное зелье защиты", class: "Зелье характеристик", effect: 8, target: "ac", price: 750},
    pprotectionPotion: {name: "Превосходное зелье защиты", class: "Зелье характеристик", effect: 12, target: "ac", price: 7500},

    strenghtPotion: {name: "Зелье силы", class: "Зелье характеристик", effect: 1, target: "strengh", price: 75},
    bstrenghtPotion: {name: "Большое зелье силы", class: "Зелье характеристик", effect: 2, target: "strengh", price: 100},
    estrenghtPotion: {name: "Отличное зелье силы", class: "Зелье характеристик", effect: 4, target: "strengh", price: 500},
    pstrenghtPotion: {name: "Превосходное зелье силы", class: "Зелье характеристик", effect: 6, target: "strengh", price: 5000},

    dexterityPotion: {name: "Зелье ловкости", class: "Зелье характеристик", effect: 1, target: "dexterity", price: 75},
    bdexterityPotion: {name: "Большое зелье ловкости", class: "Зелье характеристик", effect: 2, target: "dexterity", price: 100},
    edexterityPotion: {name: "Отличное зелье ловкости", class: "Зелье характеристик", effect: 4, target: "dexterity", price: 500},
    pdexterityPotion: {name: "Превосходное зелье ловкости", class: "Зелье характеристик", effect: 6, target: "dexterity", price: 5000},

    physiquePotion: {name: "Зелье выносливости", class: "Зелье характеристик", effect: 1, target: "physique", price: 75},
    bphysiquePotion: {name: "Большое зелье выносливости", class: "Зелье характеристик", effect: 2, target: "physique", price: 100},
    ephysiquePotion: {name: "Отличное зелье выносливости", class: "Зелье характеристик", effect: 4, target: "physique", price: 500},
    pphysiquePotion: {name: "Превосходное зелье выносливости", class: "Зелье характеристик", effect: 6, target: "physique", price: 5000},

    intelligencePotion: {name: "Зелье интеллекта", class: "Зелье характеристик", effect: 1, target: "intelligence", price: 75},
    bintelligencePotion: {name: "Большое зелье интеллекта", class: "Зелье характеристик", effect: 2, target: "intelligence", price: 100},
    eintelligencePotion: {name: "Отличное зелье интеллекта", class: "Зелье характеристик", effect: 4, target: "intelligence", price: 500},
    pintelligencePotion: {name: "Превосходное зелье интеллекта", class: "Зелье характеристик", effect: 6, target: "intelligence", price: 5000},

    wisdomPotion: {name: "Зелье мудрости", class: "Зелье характеристик", effect: 1, target: "wisdom", price: 75},
    bwisdomPotion: {name: "Большое зелье мудрости", class: "Зелье характеристик", effect: 2, target: "wisdom", price: 100},
    ewisdomPotion: {name: "Отличное зелье мудрости", class: "Зелье характеристик", effect: 4, target: "wisdom", price: 500},
    pwisdomPotion: {name: "Превосходное зелье мудрости", class: "Зелье характеристик", effect: 6, target: "wisdom", price: 5000},
    
    charismaPotion: {name: "Зелье харизмы", class: "Зелье характеристик", effect: 1, target: "charisma", price: 75},
    bcharismaPotion: {name: "Большое зелье харизмы", class: "Зелье характеристик", effect: 2, target: "charisma", price: 100},
    echarismaPotion: {name: "Отличное зелье харизмы", class: "Зелье характеристик", effect: 4, target: "charisma", price: 500},
    pcharismaPotion: {name: "Превосходное зелье харизмы", class: "Зелье характеристик", effect: 6, target: "charisma", price: 5000},


    megaPotion: {name: "Мега зелье", class: "Мега зелье", effect: 2, price: 200},
    bmegaPotion: {name: "Большое мега зелье", class: "Мега зелье", effect: 3, price: 700},
    emegaPotion: {name: "Отличное мега зелье", class: "Мега зелье", effect: 5, price: 2500},
    pmegaPotion: {name: "Превосходное мега зелье", class: "Мега зелье", effect: 8, price: 7000},


    resistancePotion: {name: "Зелье сопротивления", class: "Зелье активатор", target: "resistance", time: 3, price: 350},
    invulnerabilityPotion: {name: "Зелье неуязвимости", class: "Зелье активатор", target: "invulnerability", time: 3, price: 1700},
    spikePotion: {name: "Зелье шипов", class: "Зелье активатор", target: "spikes", time: 3, price: 1700},
    firePotion: {name: "Зелье атакующего пламени", class: "Зелье активатор", target: "fire attack", time: 3, price: 400},


    beer: {name: "Пиво", class: "Пиво", effect: 5, price: 20},
    kvas: {name: "Квас", class: "Пиво", effect: 15, price: 55},
    kumiss: {name: "Кумыс", class: "Пиво", effect: 50, price: 650},


    chaosPotion: {name: "Зелье статистического хаоса", class: "Зелье хаоса", price: 8000}
    
}


export const magicWeapon = {
    vampirKnife: {name: "Вампирский кинжал", stats: arms.simpleHandWeapons.knife, class: "Вампирское", effect: diceRandomizer(4), price: 150},
    vampirSpear: {name: "Вампирское копьё", stats: arms.simpleHandWeapons.spear, class: "Вампирское", effect: diceRandomizer(6), price: 180},
    vampirSickle: {name: "Вампирский серп", stats: arms.simpleHandWeapons.Sickle, class: "Вампирское", effect: diceRandomizer(4), price: 140},
    vampirTwoHandedSword: {name: "Вампирский двуручный меч", stats: arms.militaryHandWeapons.twoHandedSword, class: "Вампирское", effect: diceRandomizer(6, 2), price: 450},
    vampirBigAxe: {name: "Вампирская cекира", stats: arms.militaryHandWeapons.bigAxe, class: "Вампирское", effect: diceRandomizer(12), price: 700},
    vampirShortBow: {name: "Вампирский короткий лук", stats: arms.simpleRangeWeapon.shortBow, class: "Вампирское", effect: diceRandomizer(6), price: 500},
    vampirHeavyCrossbow: {name: "Вампирский тяжёлый арбалет", stats: arms.militaryRangeWeapon.heavyCrossbow, class: "Вампирское", effect: diceRandomizer(10), price: 750},
    vampirScimitar: {name: "Вампирский скимитар", stats: arms.militaryHandWeapons.scimitar, class: "Вампирское", effect: diceRandomizer(6), price: 500},
    
    bloodKnife: {name: "Кровавый кинжал", stats: arms.simpleHandWeapons.knife, class: "Вампирское", effect: diceRandomizer(8), price: 350},
    bloodSpear: {name: "Кровавое копьё", stats: arms.simpleHandWeapons.spear, class: "Вампирское", effect: diceRandomizer(12), price: 400},
    bloodSickle: {name: "Кровавый серп", stats: arms.simpleHandWeapons.Sickle, class: "Вампирское", effect: diceRandomizer(8), price: 330},
    bloodTwoHandedSword: {name: "Кровавый двуручный меч", stats: arms.militaryHandWeapons.twoHandedSword, class: "Вампирское", effect: diceRandomizer(8, 4), price: 1000},
    bloodBigAxe: {name: "Кровавая cекира", stats: arms.militaryHandWeapons.bigAxe, class: "Вампирское", effect: diceRandomizer(20), price: 1400},
    bloodShortBow: {name: "Кровавый короткий лук", stats: arms.simpleRangeWeapon.shortBow, class: "Вампирское", effect: diceRandomizer(12), price: 1000},
    bloodHeavyCrossbow: {name: "Кровавый тяжёлый арбалет", stats: arms.militaryRangeWeapon.heavyCrossbow, class: "Вампирское", effect: diceRandomizer(20), price: 1550},
    bloodScimitar: {name: "Кровавый скимитар", stats: arms.militaryHandWeapons.scimitar, class: "Вампирское", effect: diceRandomizer(12), price: 1000},
    
    lifeStealerKnife: {name: "Забирающий жизнь кинжал", stats: arms.simpleHandWeapons.knife, class: "Вампирское", effect: diceRandomizer(120), price: 800},
    lifeStealerSpear: {name: "Забирающее жизнь копьё", stats: arms.simpleHandWeapons.spear, class: "Вампирское", effect: diceRandomizer(20), price: 900},
    lifeStealerSickle: {name: "Забирающий жизнь серп", stats: arms.simpleHandWeapons.Sickle, class: "Вампирское", effect: diceRandomizer(12, 2), price: 770},
    lifeStealerTwoHandedSword: {name: "Забирающий жизнь двуручный меч", stats: arms.militaryHandWeapons.twoHandedSword, class: "Вампирское", effect: diceRandomizer(12, 4), price: 2100},
    lifeStealerBigAxe: {name: "Забирающий жизнь cекира", stats: arms.militaryHandWeapons.bigAxe, class: "Вампирское", effect: diceRandomizer(20, 2), price: 3000},
    lifeStealerShortBow: {name: "Забирающий жизнь короткий лук", stats: arms.simpleRangeWeapon.shortBow, class: "Вампирское", effect: diceRandomizer(12, 2), price: 2200},
    lifeStealerHeavyCrossbow: {name: "Забирающий жизнь тяжёлый арбалет", stats: arms.militaryRangeWeapon.heavyCrossbow, class: "Вампирское", effect: diceRandomizer(20, 2), price: 3500},
    lifeStealerScimitar: {name: "Забирающий жизнь скимитар", stats: arms.militaryHandWeapons.scimitar, class: "Вампирское", effect: diceRandomizer(12, 2), price: 2000},


    sparklingBaton: {name: "Искрящаяся дубинка", stats: arms.simpleHandWeapons.baton, class: "Огненное", effect: diceRandomizer(4), time: 2, price: 150},
    sparklingLightHammer: {name: "Искрящийся лёгкий молот", stats: arms.simpleHandWeapons.lightHammer, class: "Огненное", effect: diceRandomizer(4), time: 2, price: 180},
    sparklingClub: {name: "Искрящаяся палица", stats: arms.simpleHandWeapons.club, class: "Огненное", effect: diceRandomizer(4), time: 2, price: 180},
    sparklingHandAxe: {name: "Искрящийся ручной топор", stats: arms.simpleHandWeapons.handAxe, class: "Огненное", effect: diceRandomizer(4), time: 2, price: 270},
    sparklingBattleStaff: {name: "Искрящийся боевой посох", stats: arms.simpleHandWeapons.battleStaff, class: "Огненное", effect: diceRandomizer(4), time: 2, price: 180},
    sparklingLightCrossbow: {name: "Искрящийся легкий арбалет", stats: arms.simpleRangeWeapon.lightCrossbow, class: "Огненное", effect: diceRandomizer(4), time: 2, price: 600},
    sparklingGlaive: {name: "Искрящаяся глефа", stats: arms.militaryHandWeapons.glaive, class: "Огненное", effect: diceRandomizer(4), time: 2, price: 550},
    sparklingMorgenstern: {name: "Искрящийся моргенштерн", stats: arms.militaryHandWeapons.morgenstern, class: "Огненное", effect: diceRandomizer(4), time: 2, price: 480},
    sparklingChain: {name: "Искрящийся цеп", stats: arms.militaryHandWeapons.chain, class: "Огненное", effect: diceRandomizer(4), time: 2, price: 170},
    sparklingLongBow: {name: "Искрящийся длинный лук", stats: arms.militaryRangeWeapon.longBow, class: "Огненное", effect: diceRandomizer(4), time: 2, price: 900},

    fireBaton: {name: "Огненная дубинка", stats: arms.simpleHandWeapons.baton, class: "Огненное", effect: diceRandomizer(8), time: 5, price: 300},
    fireLightHammer: {name: "Огненный лёгкий молот", stats: arms.simpleHandWeapons.lightHammer, class: "Огненное", effect: diceRandomizer(8), time: 5, price: 360},
    fireClub: {name: "Огненная палица", stats: arms.simpleHandWeapons.club, class: "Огненное", effect: diceRandomizer(8), time: 5, price: 360},
    fireHandAxe: {name: "Огненный ручной топор", stats: arms.simpleHandWeapons.handAxe, class: "Огненное", effect: diceRandomizer(8), time: 5, price: 600},
    fireBattleStaff: {name: "Огненный боевой посох", stats: arms.simpleHandWeapons.battleStaff, class: "Огненное", effect: diceRandomizer(8), time: 5, price: 400},
    fireLightCrossbow: {name: "Огненный легкий арбалет", stats: arms.simpleRangeWeapon.lightCrossbow, class: "Огненное", effect: diceRandomizer(8), time: 5, price: 1200},
    fireGlaive: {name: "Огненная глефа", stats: arms.militaryHandWeapons.glaive, class: "Огненное", effect: diceRandomizer(8), time: 5, price: 1100},
    fireMorgenstern: {name: "Огненный моргенштерн", stats: arms.militaryHandWeapons.morgenstern, class: "Огненное", effect: diceRandomizer(8), time: 5, price: 1000},
    fireChain: {name: "Огненный цеп", stats: arms.militaryHandWeapons.chain, class: "Огненное", effect: diceRandomizer(8), time: 5, price: 400},
    fireLongBow: {name: "Огненный длинный лук", stats: arms.militaryRangeWeapon.longBow, class: "Огненное", effect: diceRandomizer(8), time: 5, price: 1800},

    sizzlingBaton: {name: "Испепелящая дубинка", stats: arms.simpleHandWeapons.baton, class: "Огненное", effect: diceRandomizer(20), time: 6, price: 650},
    sizzlingLightHammer: {name: "Испепелящий лёгкий молот", stats: arms.simpleHandWeapons.lightHammer, class: "Огненное", effect: diceRandomizer(20), time: 6, price: 800},
    sizzlingClub: {name: "Испепелящая палица", stats: arms.simpleHandWeapons.club, class: "Огненное", effect: diceRandomizer(20), time: 6, price: 800},
    sizzlingHandAxe: {name: "Испепелящий ручной топор", stats: arms.simpleHandWeapons.handAxe, class: "Огненное", effect: diceRandomizer(20), time: 6, price: 1200},
    sizzlingBattleStaff: {name: "Испепелящий боевой посох", stats: arms.simpleHandWeapons.battleStaff, class: "Огненное", effect: diceRandomizer(20), time: 6, price: 800},
    sizzlingLightCrossbow: {name: "Испепелящий легкий арбалет", stats: arms.simpleRangeWeapon.lightCrossbow, class: "Огненное", effect: diceRandomizer(20), time: 6, price: 2500},
    sizzlingGlaive: {name: "Испепелящая глефа", stats: arms.militaryHandWeapons.glaive, class: "Огненное", effect: diceRandomizer(20), time: 6, price: 2300},
    sizzlingMorgenstern: {name: "Испепелящий моргенштерн", stats: arms.militaryHandWeapons.morgenstern, class: "Огненное", effect: diceRandomizer(20), time: 6, price: 2000},
    sizzlingChain: {name: "Испепелящий цеп", stats: arms.militaryHandWeapons.chain, class: "Огненное", effect: diceRandomizer(20), time: 6, price: 850},
    sizzlingLongBow: {name: "Испепелящий длинный лук", stats: arms.militaryRangeWeapon.longBow, class: "Огненное", effect: diceRandomizer(20), time: 6, price: 4000},


    poisonedMace: {name: "Отравленная булова", stats: arms.simpleHandWeapons.mace, class: "Отравленное", effect: 3, price: 200},
    poisonedPropellantSpear: {name: "Отравленное метательное копье", stats: arms.simpleHandWeapons.propellantSpear, class: "Отравленное", effect: 3, price: 300},
    poisonedSling: {name: "Отравленная праща", stats: arms.simpleRangeWeapon.sling, class: "Отравленное", effect: 3, price: 220},
    poisonedHalberd: {name: "Отравленная алебарда", stats: arms.militaryHandWeapons.halberd, class: "Отравленное", effect: 3, price: 600},
    poisonedWarHammer: {name: "Отравленный боевой молот", stats: arms.militaryHandWeapons.warHammer, class: "Отравленное", effect: 3, price: 450},
    poisonedLongSpear: {name: "Отравленое длинное копье", stats: arms.militaryHandWeapons.longSpear, class: "Отравленное", effect: 3, price: 350},
    poisonedBlowpipe: {name: "Отравленная духовая трубка", stats: arms.militaryRangeWeapon.blowpipe, class: "Отравленное", effect: 3, price: 350},
    poisonedRapier: {name: "Отравленная рапира", stats: arms.militaryHandWeapons.rapier, class: "Отравленное", effect: 3, price: 700},
    
    venomousMace: {name: "Ядовитая булова", stats: arms.simpleHandWeapons.mace, class: "Отравленное", effect: 7, price: 450},
    venomousPropellantSpear: {name: "Ядовитое метательное копье", stats: arms.simpleHandWeapons.propellantSpear, class: "Отравленное", effect: 7, price: 450},
    venomousSling: {name: "Ядовитая праща", stats: arms.simpleRangeWeapon.sling, class: "Отравленное", effect: 7, price: 500},
    venomousHalberd: {name: "Ядовитая алебарда", stats: arms.militaryHandWeapons.halberd, class: "Отравленное", effect: 7, price: 1200},
    venomousWarHammer: {name: "Ядовитый боевой молот", stats: arms.militaryHandWeapons.warHammer, class: "Отравленное", effect: 7, price: 900},
    venomousLongSpear: {name: "Ядовитое длинное копье", stats: arms.militaryHandWeapons.longSpear, class: "Отравленное", effect: 7, price: 800},
    venomousBlowpipe: {name: "Ядовитая духовая трубка", stats: arms.militaryRangeWeapon.blowpipe, class: "Отравленное", effect: 7, price: 750},
    venomousRapier: {name: "Ядовитая рапира", stats: arms.militaryHandWeapons.rapier, class: "Отравленное", effect: 7, price: 1450},

    acidicMace: {name: "Кислотная булова", stats: arms.simpleHandWeapons.mace, class: "Отравленное", effect: 15, price: 900},
    acidicPropellantSpear: {name: "Кислотное метательное копье", stats: arms.simpleHandWeapons.propellantSpear, class: "Отравленное", effect: 15, price: 850},
    acidicSling: {name: "Кислотная праща", stats: arms.simpleRangeWeapon.sling, class: "Отравленное", effect: 15, price: 1000},
    acidicHalberd: {name: "Кислотная алебарда", stats: arms.militaryHandWeapons.halberd, class: "Отравленное", effect: 15, price: 2500},
    acidicWarHammer: {name: "Кислотный боевой молот", stats: arms.militaryHandWeapons.warHammer, class: "Отравленное", effect: 15, price: 1800},
    acidicLongSpear: {name: "Кислотное длинное копье", stats: arms.militaryHandWeapons.longSpear, class: "Отравленное", effect: 15, price: 1600},
    acidicBlowpipe: {name: "Кислотная духовая трубка", stats: arms.militaryRangeWeapon.blowpipe, class: "Отравленное", effect: 15, price: 1500},
    acidicRapier: {name: "Кислотная рапира", stats: arms.militaryHandWeapons.rapier, class: "Отравленное", effect: 15, price: 2900},


    tactiсTrident: {name: "Тактический трезубец", stats: arms.militaryHandWeapons.trident, class: "Тактическое", effect: 1, price: 250},
    tactiсHandCrossbow: {name: "Тактический ручной арбалет", stats: arms.militaryRangeWeapon.handCrossbow, class: "Тактическое", effect: 1, price: 1500},
    tactiсPeak: {name: "Тактический пика", stats: arms.militaryHandWeapons.peak, class: "Тактическое", effect: 1, price: 300},
    tactiсHammer: {name: "Тактический молот", stats: arms.militaryHandWeapons.hammer, class: "Тактическое", effect: 1, price: 450},
    tactiсShortSword: {name: "Тактический короткий меч", stats: arms.militaryHandWeapons.shortSword, class: "Тактическое", effect: 1, price: 300},
    tactiсWhip: {name: "Тактический кнут", stats: arms.militaryHandWeapons.whip, class: "Тактическое", effect: 1, price: 200},
    tactiсLongSword: {name: "Тактический длинный меч", stats: arms.militaryHandWeapons.longSword, class: "Тактическое", effect: 1, price: 370},
    tactiсWarAxe: {name: "Тактический боевой топор", stats: arms.militaryHandWeapons.warAxe, class: "Тактическое", effect: 1, price: 300},
    tactiсBreakattlePickaxe: {name: "Тактический боевая кирка", stats: arms.militaryHandWeapons.breakattlePickaxe, class: "Тактическое", effect: 1, price: 250}

}

export const magicArmor = {
    strenghtQuiltedArmor: {name: "Стеганный доспех силы", stats: armors.lightArmor.quiltedArmor, class: "Доспех характеристик", effect: 2, target: "strengh", price: 300},
    strenghtLeatherArmor: {name: "Кожанный доспех силы", stats: armors.lightArmor.leatherArmor, class: "Доспех характеристик", effect: 2, target: "strengh", price: 600},
    strenghtRevetedLeatherArmor: {name: "Проклепанный кожанный доспех силы", stats: armors.lightArmor.revetedLeatherArmor, class: "Доспех характеристик", effect: 2, target: "strengh", price: 1600},
    strenghtSelfishArmor: {name: "Шкурный доспех силы", stats: armors.mediumArmor.selfishArmor, class: "Доспех характеристик", effect: 2, target: "strengh", price: 600},
    strenghtChainmailShirt: {name: "Кольчужная рубаха силы", stats: armors.mediumArmor.chainmailShirt, class: "Доспех характеристик", effect: 2, target: "strengh", price: 2000},
    strenghtScalyArmor: {name: "Чешуйчатый доспех силы", stats: armors.mediumArmor.scalyArmor, class: "Доспех характеристик", effect: 2, target: "strengh", price: 2000},
    strenghtCuirass: {name: "Кираса силы", stats: armors.mediumArmor.cuirass, class: "Доспех характеристик", effect: 2, target: "strengh", price: 5900},
    strenghtHalfPlateArmor: {name: "Полулаты силы", stats: armors.mediumArmor.halfPlateArmor, class: "Доспех характеристик", effect: 2, target: "strengh", price: 8000},
    strenghtRingShapedArmor: {name: "Колечный доспех силы", stats: armors.heavyArmor.ringShapedArmor, class: "Доспех характеристик", effect: 2, target: "strengh", price: 1800},
    strenghtChainmail: {name: "Кольчуга силы", stats: armors.heavyArmor.chainmail, class: "Доспех характеристик", effect: 2, target: "strengh", price: 2600},
    strenghtStackedArmor: {name: "Наборный доспех силы", stats: armors.heavyArmor.stackedArmor, class: "Доспех характеристик", effect: 2, target: "strengh", price: 4600},
    strenghtPlateArmor: {name: "Латы силы", stats: armors.heavyArmor.plateArmor, class: "Доспех характеристик", effect: 2, target: "strengh", price: 11000},
    strenghtShield: {name: "Щит силы", stats: armors.shield, class: "Доспех характеристик", effect: 2, target: "strengh", price: 600},

    powerQuiltedArmor: {name: "Стеганный доспех мощи", stats: armors.lightArmor.quiltedArmor, class: "Доспех характеристик", effect: 3, target: "strengh", price: 600},
    powerLeatherArmor: {name: "Кожанный доспех мощи", stats: armors.lightArmor.leatherArmor, class: "Доспех характеристик", effect: 3, target: "strengh", price: 1200},
    powerRevetedLeatherArmor: {name: "Проклепанный кожанный доспех мощи", stats: armors.lightArmor.revetedLeatherArmor, class: "Доспех характеристик", effect: 3, target: "strengh", price: 3200},
    powerSelfishArmor: {name: "Шкурный доспех мощи", stats: armors.mediumArmor.selfishArmor, class: "Доспех характеристик", effect: 3, target: "strengh", price: 1200},
    powerChainmailShirt: {name: "Кольчужная рубаха мощи", stats: armors.mediumArmor.chainmailShirt, class: "Доспех характеристик", effect: 3, target: "strengh", price: 4000},
    powerScalyArmor: {name: "Чешуйчатый доспех мощи", stats: armors.mediumArmor.scalyArmor, class: "Доспех характеристик", effect: 3, target: "strengh", price: 4000},
    powerCuirass: {name: "Кираса мощи", stats: armors.mediumArmor.cuirass, class: "Доспех характеристик", effect: 3, target: "strengh", price: 12000},
    powerHalfPlateArmor: {name: "Полулаты мощи", stats: armors.mediumArmor.halfPlateArmor, class: "Доспех характеристик", effect: 3, target: "strengh", price: 16000},
    powerRingShapedArmor: {name: "Колечный доспех мощи", stats: armors.heavyArmor.ringShapedArmor, class: "Доспех характеристик", effect: 3, target: "strengh", price: 3600},
    powerChainmail: {name: "Кольчуга мощи", stats: armors.heavyArmor.chainmail, class: "Доспех характеристик", effect: 3, target: "strengh", price: 5200},
    powerStackedArmor: {name: "Наборный доспех мощи", stats: armors.heavyArmor.stackedArmor, class: "Доспех характеристик", effect: 3, target: "strengh", price: 9200},
    powerPlateArmor: {name: "Латы мощи", stats: armors.heavyArmor.plateArmor, class: "Доспех характеристик", effect: 3, target: "strengh", price: 22000},
    powerShield: {name: "Щит мощи", stats: armors.shield, class: "Доспех характеристик", effect: 3, target: "strengh", price: 1200},


    dexterityQuiltedArmor: {name: "Стеганный доспех ловкости", stats: armors.lightArmor.quiltedArmor, class: "Доспех характеристик", effect: 2, target: "dexterity", price: 300},
    dexterityLeatherArmor: {name: "Кожанный доспех ловкости", stats: armors.lightArmor.leatherArmor, class: "Доспех характеристик", effect: 2, target: "dexterity", price: 600},
    dexterityRevetedLeatherArmor: {name: "Проклепанный кожанный доспех ловкости", stats: armors.lightArmor.revetedLeatherArmor, class: "Доспех характеристик", effect: 2, target: "dexterity", price: 1600},
    dexteritySelfishArmor: {name: "Шкурный доспех ловкости", stats: armors.mediumArmor.selfishArmor, class: "Доспех характеристик", effect: 2, target: "dexterity", price: 600},
    dexterityChainmailShirt: {name: "Кольчужная рубаха ловкости", stats: armors.mediumArmor.chainmailShirt, class: "Доспех характеристик", effect: 2, target: "dexterity", price: 2000},
    dexterityScalyArmor: {name: "Чешуйчатый доспех ловкости", stats: armors.mediumArmor.scalyArmor, class: "Доспех характеристик", effect: 2, target: "dexterity", price: 2000},
    dexterityCuirass: {name: "Кираса ловкости", stats: armors.mediumArmor.cuirass, class: "Доспех характеристик", effect: 2, target: "dexterity", price: 5900},
    dexterityHalfPlateArmor: {name: "Полулаты ловкости", stats: armors.mediumArmor.halfPlateArmor, class: "Доспех характеристик", effect: 2, target: "dexterity", price: 8000},
    dexterityRingShapedArmor: {name: "Колечный доспех ловкости", stats: armors.heavyArmor.ringShapedArmor, class: "Доспех характеристик", effect: 2, target: "dexterity", price: 1800},
    dexterityChainmail: {name: "Кольчуга ловкости", stats: armors.heavyArmor.chainmail, class: "Доспех характеристик", effect: 2, target: "dexterity", price: 2600},
    dexterityStackedArmor: {name: "Наборный доспех ловкости", stats: armors.heavyArmor.stackedArmor, class: "Доспех характеристик", effect: 2, target: "dexterity", price: 4600},
    dexterityPlateArmor: {name: "Латы ловкости", stats: armors.heavyArmor.plateArmor, class: "Доспех характеристик", effect: 2, target: "dexterity", price: 11000},
    dexterityShield: {name: "Щит ловкости", stats: armors.shield, class: "Доспех характеристик", effect: 2, target: "dexterity", price: 600},

    stealthQuiltedArmor: {name: "Стеганный доспех скрытности", stats: armors.lightArmor.quiltedArmor, class: "Доспех характеристик", effect: 3, target: "dexterity", price: 600},
    stealthLeatherArmor: {name: "Кожанный доспех скрытности", stats: armors.lightArmor.leatherArmor, class: "Доспех характеристик", effect: 3, target: "dexterity", price: 1200},
    stealthRevetedLeatherArmor: {name: "Проклепанный кожанный доспех скрытности", stats: armors.lightArmor.revetedLeatherArmor, class: "Доспех характеристик", effect: 3, target: "dexterity", price: 3200},
    stealthSelfishArmor: {name: "Шкурный доспех скрытности", stats: armors.mediumArmor.selfishArmor, class: "Доспех характеристик", effect: 3, target: "dexterity", price: 1200},
    stealthChainmailShirt: {name: "Кольчужная рубаха скрытности", stats: armors.mediumArmor.chainmailShirt, class: "Доспех характеристик", effect: 3, target: "dexterity", price: 4000},
    stealthScalyArmor: {name: "Чешуйчатый доспех скрытности", stats: armors.mediumArmor.scalyArmor, class: "Доспех характеристик", effect: 3, target: "dexterity", price: 4000},
    stealthCuirass: {name: "Кираса скрытности", stats: armors.mediumArmor.cuirass, class: "Доспех характеристик", effect: 3, target: "dexterity", price: 12000},
    stealthHalfPlateArmor: {name: "Полулаты скрытности", stats: armors.mediumArmor.halfPlateArmor, class: "Доспех характеристик", effect: 3, target: "dexterity", price: 16000},
    stealthRingShapedArmor: {name: "Колечный доспех скрытности", stats: armors.heavyArmor.ringShapedArmor, class: "Доспех характеристик", effect: 3, target: "dexterity", price: 3600},
    stealthChainmail: {name: "Кольчуга скрытности", stats: armors.heavyArmor.chainmail, class: "Доспех характеристик", effect: 3, target: "dexterity", price: 5200},
    stealthStackedArmor: {name: "Наборный доспех скрытности", stats: armors.heavyArmor.stackedArmor, class: "Доспех характеристик", effect: 3, target: "dexterity", price: 9200},
    stealthPlateArmor: {name: "Латы скрытности", stats: armors.heavyArmor.plateArmor, class: "Доспех характеристик", effect: 3, target: "dexterity", price: 22000},
    stealthShield: {name: "Щит скрытности", stats: armors.shield, class: "Доспех характеристик", effect: 3, target: "dexterity", price: 1200},


    physiqueQuiltedArmor: {name: "Стеганный доспех телосложения", stats: armors.lightArmor.quiltedArmor, class: "Доспех характеристик", effect: 2, target: "physique", price: 300},
    physiqueLeatherArmor: {name: "Кожанный доспех телосложения", stats: armors.lightArmor.leatherArmor, class: "Доспех характеристик", effect: 2, target: "physique", price: 600},
    physiqueRevetedLeatherArmor: {name: "Проклепанный кожанный доспех телосложения", stats: armors.lightArmor.revetedLeatherArmor, class: "Доспех характеристик", effect: 2, target: "physique", price: 1600},
    physiqueSelfishArmor: {name: "Шкурный доспех телосложения", stats: armors.mediumArmor.selfishArmor, class: "Доспех характеристик", effect: 2, target: "physique", price: 600},
    physiqueChainmailShirt: {name: "Кольчужная рубаха телосложения", stats: armors.mediumArmor.chainmailShirt, class: "Доспех характеристик", effect: 2, target: "physique", price: 2000},
    physiqueScalyArmor: {name: "Чешуйчатый доспех телосложения", stats: armors.mediumArmor.scalyArmor, class: "Доспех характеристик", effect: 2, target: "physique", price: 2000},
    physiqueCuirass: {name: "Кираса телосложения", stats: armors.mediumArmor.cuirass, class: "Доспех характеристик", effect: 2, target: "physique", price: 5900},
    physiqueHalfPlateArmor: {name: "Полулаты телосложения", stats: armors.mediumArmor.halfPlateArmor, class: "Доспех характеристик", effect: 2, target: "physique", price: 8000},
    physiqueRingShapedArmor: {name: "Колечный доспех телосложения", stats: armors.heavyArmor.ringShapedArmor, class: "Доспех характеристик", effect: 2, target: "physique", price: 1800},
    physiqueChainmail: {name: "Кольчуга телосложения", stats: armors.heavyArmor.chainmail, class: "Доспех характеристик", effect: 2, target: "physique", price: 2600},
    physiqueStackedArmor: {name: "Наборный доспех телосложения", stats: armors.heavyArmor.stackedArmor, class: "Доспех характеристик", effect: 2, target: "physique", price: 4600},
    physiquePlateArmor: {name: "Латы телосложения", stats: armors.heavyArmor.plateArmor, class: "Доспех характеристик", effect: 2, target: "physique", price: 11000},
    physiqueShield: {name: "Щит телосложения", stats: armors.shield, class: "Доспех характеристик", effect: 2, target: "strengh", price: 600},

    enduranceQuiltedArmor: {name: "Стеганный доспех прочности", stats: armors.lightArmor.quiltedArmor, class: "Доспех характеристик", effect: 3, target: "physique", price: 600},
    enduranceLeatherArmor: {name: "Кожанный доспех прочности", stats: armors.lightArmor.leatherArmor, class: "Доспех характеристик", effect: 3, target: "physique", price: 1200},
    enduranceRevetedLeatherArmor: {name: "Проклепанный кожанный доспех прочности", stats: armors.lightArmor.revetedLeatherArmor, class: "Доспех характеристик", effect: 3, target: "physique", price: 3200},
    enduranceSelfishArmor: {name: "Шкурный доспех прочности", stats: armors.mediumArmor.selfishArmor, class: "Доспех характеристик", effect: 3, target: "physique", price: 1200},
    enduranceChainmailShirt: {name: "Кольчужная рубаха прочности", stats: armors.mediumArmor.chainmailShirt, class: "Доспех характеристик", effect: 3, target: "physique", price: 4000},
    enduranceScalyArmor: {name: "Чешуйчатый доспех прочности", stats: armors.mediumArmor.scalyArmor, class: "Доспех характеристик", effect: 3, target: "physique", price: 4000},
    enduranceCuirass: {name: "Кираса прочности", stats: armors.mediumArmor.cuirass, class: "Доспех характеристик", effect: 3, target: "physique", price: 12000},
    enduranceHalfPlateArmor: {name: "Полулаты прочности", stats: armors.mediumArmor.halfPlateArmor, class: "Доспех характеристик", effect: 3, target: "strephysiquengh", price: 16000},
    enduranceRingShapedArmor: {name: "Колечный доспех прочности", stats: armors.heavyArmor.ringShapedArmor, class: "Доспех характеристик", effect: 3, target: "physique", price: 3600},
    enduranceChainmail: {name: "Кольчуга прочности", stats: armors.heavyArmor.chainmail, class: "Доспех характеристик", effect: 3, target: "physique", price: 5200},
    enduranceStackedArmor: {name: "Наборный доспех прочности", stats: armors.heavyArmor.stackedArmor, class: "Доспех характеристик", effect: 3, target: "physique", price: 9200},
    endurancePlateArmor: {name: "Латы прочности", stats: armors.heavyArmor.plateArmor, class: "Доспех характеристик", effect: 3, target: "physique", price: 22000},
    enduranceShield: {name: "Щит прочности", stats: armors.shield, class: "Доспех характеристик", effect: 3, target: "physique", price: 1200},


    intelligenceQuiltedArmor: {name: "Стеганный доспех интеллекта", stats: armors.lightArmor.quiltedArmor, class: "Доспех характеристик", effect: 2, target: "intelligence", price: 300},
    intelligenceLeatherArmor: {name: "Кожанный доспех интеллекта", stats: armors.lightArmor.leatherArmor, class: "Доспех характеристик", effect: 2, target: "intelligence", price: 600},
    intelligenceRevetedLeatherArmor: {name: "Проклепанный кожанный доспех интеллекта", stats: armors.lightArmor.revetedLeatherArmor, class: "Доспех характеристик", effect: 2, target: "intelligence", price: 1600},
    intelligenceSelfishArmor: {name: "Шкурный доспех интеллекта", stats: armors.mediumArmor.selfishArmor, class: "Доспех характеристик", effect: 2, target: "intelligence", price: 600},
    intelligenceChainmailShirt: {name: "Кольчужная рубаха интеллекта", stats: armors.mediumArmor.chainmailShirt, class: "Доспех характеристик", effect: 2, target: "intelligence", price: 2000},
    intelligenceScalyArmor: {name: "Чешуйчатый доспех интеллекта", stats: armors.mediumArmor.scalyArmor, class: "Доспех характеристик", effect: 2, target: "intelligence", price: 2000},
    intelligenceCuirass: {name: "Кираса интеллекта", stats: armors.mediumArmor.cuirass, class: "Доспех характеристик", effect: 2, target: "intelligence", price: 5900},
    intelligenceHalfPlateArmor: {name: "Полулаты интеллекта", stats: armors.mediumArmor.halfPlateArmor, class: "Доспех характеристик", effect: 2, target: "intelligence", price: 8000},
    intelligenceRingShapedArmor: {name: "Колечный доспех интеллекта", stats: armors.heavyArmor.ringShapedArmor, class: "Доспех характеристик", effect: 2, target: "intelligence", price: 1800},
    intelligenceChainmail: {name: "Кольчуга интеллекта", stats: armors.heavyArmor.chainmail, class: "Доспех характеристик", effect: 2, target: "intelligence", price: 2600},
    intelligenceStackedArmor: {name: "Наборный доспех интеллекта", stats: armors.heavyArmor.stackedArmor, class: "Доспех характеристик", effect: 2, target: "intelligence", price: 4600},
    intelligencePlateArmor: {name: "Латы интеллекта", stats: armors.heavyArmor.plateArmor, class: "Доспех характеристик", effect: 2, target: "intelligence", price: 11000},
    intelligenceShield: {name: "Щит интеллекта", stats: armors.shield, class: "Доспех характеристик", effect: 2, target: "intelligence", price: 600},

    higherIntelligenceQuiltedArmor: {name: "Стеганный доспех высшего разума", stats: armors.lightArmor.quiltedArmor, class: "Доспех характеристик", effect: 3, target: "intelligence", price: 600},
    higherIntelligenceLeatherArmor: {name: "Кожанный доспех высшего разума", stats: armors.lightArmor.leatherArmor, class: "Доспех характеристик", effect: 3, target: "intelligence", price: 1200},
    higherIntelligenceRevetedLeatherArmor: {name: "Проклепанный кожанный доспех высшего разума", stats: armors.lightArmor.revetedLeatherArmor, class: "Доспех характеристик", effect: 3, target: "intelligence", price: 3200},
    higherIntelligenceSelfishArmor: {name: "Шкурный доспех высшего разума", stats: armors.mediumArmor.selfishArmor, class: "Доспех характеристик", effect: 3, target: "intelligence", price: 1200},
    higherIntelligenceChainmailShirt: {name: "Кольчужная рубаха высшего разума", stats: armors.mediumArmor.chainmailShirt, class: "Доспех характеристик", effect: 3, target: "intelligence", price: 4000},
    higherIntelligenceScalyArmor: {name: "Чешуйчатый доспех высшего разума", stats: armors.mediumArmor.scalyArmor, class: "Доспех характеристик", effect: 3, target: "intelligence", price: 4000},
    higherIntelligenceCuirass: {name: "Кираса высшего разума", stats: armors.mediumArmor.cuirass, class: "Доспех характеристик", effect: 3, target: "intelligence", price: 12000},
    higherIntelligenceHalfPlateArmor: {name: "Полулаты высшего разума", stats: armors.mediumArmor.halfPlateArmor, class: "Доспех характеристик", effect: 3, target: "intelligence", price: 16000},
    higherIntelligenceRingShapedArmor: {name: "Колечный доспех высшего разума", stats: armors.heavyArmor.ringShapedArmor, class: "Доспех характеристик", effect: 3, target: "intelligence", price: 3600},
    higherIntelligenceChainmail: {name: "Кольчуга высшего разума", stats: armors.heavyArmor.chainmail, class: "Доспех характеристик", effect: 3, target: "intelligence", price: 5200},
    higherIntelligenceStackedArmor: {name: "Наборный доспех высшего разума", stats: armors.heavyArmor.stackedArmor, class: "Доспех характеристик", effect: 3, target: "intelligence", price: 9200},
    higherIntelligencePlateArmor: {name: "Латы высшего разума", stats: armors.heavyArmor.plateArmor, class: "Доспех характеристик", effect: 3, target: "intelligence", price: 22000},
    higherIntelligenceShield: {name: "Щит высшего разума", stats: armors.shield, class: "Доспех характеристик", effect: 3, target: "intelligence", price: 1200},


    wisdomQuiltedArmor: {name: "Стеганный доспех мудрости", stats: armors.lightArmor.quiltedArmor, class: "Доспех характеристик", effect: 2, target: "wisdom", price: 300},
    wisdomLeatherArmor: {name: "Кожанный доспех мудрости", stats: armors.lightArmor.leatherArmor, class: "Доспех характеристик", effect: 2, target: "wisdom", price: 600},
    wisdomRevetedLeatherArmor: {name: "Проклепанный кожанный доспех мудрости", stats: armors.lightArmor.revetedLeatherArmor, class: "Доспех характеристик", effect: 2, target: "wisdom", price: 1600},
    wisdomSelfishArmor: {name: "Шкурный доспех мудрости", stats: armors.mediumArmor.selfishArmor, class: "Доспех характеристик", effect: 2, target: "wisdom", price: 600},
    wisdomChainmailShirt: {name: "Кольчужная рубаха мудрости", stats: armors.mediumArmor.chainmailShirt, class: "Доспех характеристик", effect: 2, target: "wisdom", price: 2000},
    wisdomScalyArmor: {name: "Чешуйчатый доспех мудрости", stats: armors.mediumArmor.scalyArmor, class: "Доспех характеристик", effect: 2, target: "wisdom", price: 2000},
    wisdomCuirass: {name: "Кираса мудрости", stats: armors.mediumArmor.cuirass, class: "Доспех характеристик", effect: 2, target: "wisdom", price: 5900},
    wisdomHalfPlateArmor: {name: "Полулаты мудрости", stats: armors.mediumArmor.halfPlateArmor, class: "Доспех характеристик", effect: 2, target: "wisdom", price: 8000},
    wisdomRingShapedArmor: {name: "Колечный доспех мудрости", stats: armors.heavyArmor.ringShapedArmor, class: "Доспех характеристик", effect: 2, target: "wisdom", price: 1800},
    wisdomChainmail: {name: "Кольчуга мудрости", stats: armors.heavyArmor.chainmail, class: "Доспех характеристик", effect: 2, target: "wisdom", price: 2600},
    wisdomStackedArmor: {name: "Наборный доспех мудрости", stats: armors.heavyArmor.stackedArmor, class: "Доспех характеристик", effect: 2, target: "wisdom", price: 4600},
    wisdomPlateArmor: {name: "Латы мудрости", stats: armors.heavyArmor.plateArmor, class: "Доспех характеристик", effect: 2, target: "wisdom", price: 11000},
    wisdomShield: {name: "Щит мудрости", stats: armors.shield, class: "Доспех характеристик", effect: 2, target: "wisdom", price: 600},

    clearVisionQuiltedArmor: {name: "Стеганный доспех ясновидения", stats: armors.lightArmor.quiltedArmor, class: "Доспех характеристик", effect: 3, target: "wisdom", price: 600},
    clearVisionLeatherArmor: {name: "Кожанный доспех ясновидения", stats: armors.lightArmor.leatherArmor, class: "Доспех характеристик", effect: 3, target: "wisdom", price: 1200},
    clearVisionRevetedLeatherArmor: {name: "Проклепанный кожанный доспех ясновидения", stats: armors.lightArmor.revetedLeatherArmor, class: "Доспех характеристик", effect: 3, target: "wisdom", price: 3200},
    clearVisionrSelfishArmor: {name: "Шкурный доспех ясновидения", stats: armors.mediumArmor.selfishArmor, class: "Доспех характеристик", effect: 3, target: "wisdom", price: 1200},
    clearVisionChainmailShirt: {name: "Кольчужная рубаха ясновидения", stats: armors.mediumArmor.chainmailShirt, class: "Доспех характеристик", effect: 3, target: "wisdom", price: 4000},
    clearVisionScalyArmor: {name: "Чешуйчатый доспех ясновидения", stats: armors.mediumArmor.scalyArmor, class: "Доспех характеристик", effect: 3, target: "wisdom", price: 4000},
    clearVisionCuirass: {name: "Кираса ясновидения", stats: armors.mediumArmor.cuirass, class: "Доспех характеристик", effect: 3, target: "wisdom", price: 12000},
    clearVisionHalfPlateArmor: {name: "Полулаты ясновидения", stats: armors.mediumArmor.halfPlateArmor, class: "Доспех характеристик", effect: 3, target: "wisdom", price: 16000},
    clearVisionRingShapedArmor: {name: "Колечный доспех ясновидения", stats: armors.heavyArmor.ringShapedArmor, class: "Доспех характеристик", effect: 3, target: "wisdom", price: 3600},
    clearVisionChainmail: {name: "Кольчуга ясновидения", stats: armors.heavyArmor.chainmail, class: "Доспех характеристик", effect: 3, target: "wisdom", price: 5200},
    clearVisionStackedArmor: {name: "Наборный доспех ясновидения", stats: armors.heavyArmor.stackedArmor, class: "Доспех характеристик", effect: 3, target: "wisdom", price: 9200},
    clearVisionPlateArmor: {name: "Латы ясновидения", stats: armors.heavyArmor.plateArmor, class: "Доспех характеристик", effect: 3, target: "wisdom", price: 22000},
    clearVisionShield: {name: "Щит ясновидения", stats: armors.shield, class: "Доспех характеристик", effect: 3, target: "wisdom", price: 1200},


    charismaQuiltedArmor: {name: "Стеганный доспех харизмы", stats: armors.lightArmor.quiltedArmor, class: "Доспех характеристик", effect: 2, target: "charisma", price: 300},
    charismaLeatherArmor: {name: "Кожанный доспех харизмы", stats: armors.lightArmor.leatherArmor, class: "Доспех характеристик", effect: 2, target: "charisma", price: 600},
    charismaRevetedLeatherArmor: {name: "Проклепанный кожанный доспех харизмы", stats: armors.lightArmor.revetedLeatherArmor, class: "Доспех характеристик", effect: 2, target: "charisma", price: 1600},
    charismaSelfishArmor: {name: "Шкурный доспех харизмы", stats: armors.mediumArmor.selfishArmor, class: "Доспех характеристик", effect: 2, target: "charisma", price: 600},
    charismaChainmailShirt: {name: "Кольчужная рубаха харизмы", stats: armors.mediumArmor.chainmailShirt, class: "Доспех характеристик", effect: 2, target: "charisma", price: 2000},
    charismaScalyArmor: {name: "Чешуйчатый доспех харизмы", stats: armors.mediumArmor.scalyArmor, class: "Доспех характеристик", effect: 2, target: "charisma", price: 2000},
    charismaCuirass: {name: "Кираса харизмы", stats: armors.mediumArmor.cuirass, class: "Доспех характеристик", effect: 2, target: "charisma", price: 5900},
    charismaHalfPlateArmor: {name: "Полулаты харизмы", stats: armors.mediumArmor.halfPlateArmor, class: "Доспех характеристик", effect: 2, target: "charisma", price: 8000},
    charismaRingShapedArmor: {name: "Колечный доспех харизмы", stats: armors.heavyArmor.ringShapedArmor, class: "Доспех характеристик", effect: 2, target: "charisma", price: 1800},
    charismaChainmail: {name: "Кольчуга харизмы", stats: armors.heavyArmor.chainmail, class: "Доспех характеристик", effect: 2, target: "charisma", price: 2600},
    charismaStackedArmor: {name: "Наборный доспех харизмы", stats: armors.heavyArmor.stackedArmor, class: "Доспех характеристик", effect: 2, target: "charisma", price: 4600},
    charismaPlateArmor: {name: "Латы харизмы", stats: armors.heavyArmor.plateArmor, class: "Доспех характеристик", effect: 2, target: "charisma", price: 11000},
    charismaShield: {name: "Щит харизмы", stats: armors.shield, class: "Доспех характеристик", effect: 2, target: "charisma", price: 600},

    eloquenceQuiltedArmor: {name: "Стеганный доспех красноречия", stats: armors.lightArmor.quiltedArmor, class: "Доспех характеристик", effect: 3, target: "charisma", price: 600},
    eloquenceLeatherArmor: {name: "Кожанный доспех красноречия", stats: armors.lightArmor.leatherArmor, class: "Доспех характеристик", effect: 3, target: "charisma", price: 1200},
    eloquenceRevetedLeatherArmor: {name: "Проклепанный кожанный доспех красноречия", stats: armors.lightArmor.revetedLeatherArmor, class: "Доспех характеристик", effect: 3, target: "charisma", price: 3200},
    eloquenceSelfishArmor: {name: "Шкурный доспех красноречия", stats: armors.mediumArmor.selfishArmor, class: "Доспех характеристик", effect: 3, target: "charisma", price: 1200},
    eloquenceChainmailShirt: {name: "Кольчужная рубаха красноречия", stats: armors.mediumArmor.chainmailShirt, class: "Доспех характеристик", effect: 3, target: "charisma", price: 4000},
    eloquenceScalyArmor: {name: "Чешуйчатый доспех красноречия", stats: armors.mediumArmor.scalyArmor, class: "Доспех характеристик", effect: 3, target: "charisma", price: 4000},
    eloquencerCuirass: {name: "Кираса красноречия", stats: armors.mediumArmor.cuirass, class: "Доспех характеристик", effect: 3, target: "charisma", price: 12000},
    eloquenceHalfPlateArmor: {name: "Полулаты красноречия", stats: armors.mediumArmor.halfPlateArmor, class: "Доспех характеристик", effect: 3, target: "charisma", price: 16000},
    eloquenceRingShapedArmor: {name: "Колечный доспех красноречия", stats: armors.heavyArmor.ringShapedArmor, class: "Доспех характеристик", effect: 3, target: "charisma", price: 3600},
    eloquenceChainmail: {name: "Кольчуга красноречия", stats: armors.heavyArmor.chainmail, class: "Доспех характеристик", effect: 3, target: "charisma", price: 5200},
    eloquenceStackedArmor: {name: "Наборный доспех красноречия", stats: armors.heavyArmor.stackedArmor, class: "Доспех характеристик", effect: 3, target: "charisma", price: 9200},
    eloquencePlateArmor: {name: "Латы красноречия", stats: armors.heavyArmor.plateArmor, class: "Доспех характеристик", effect: 3, target: "charisma", price: 22000},
    eloquenceShield: {name: "Щит красноречия", stats: armors.shield, class: "Доспех характеристик", effect: 3, target: "charisma", price: 1200},
}


export const magicstaffs = {
    basicMagicStaff: {name: "Базовый посох магии", class: "Магический посох", spalls: [spalls.electricDischarge1, spalls.magicPlates1, spalls.healingSwing1], charge: 5, price: 300},
    basicHealStaff: {name: "Базовый посох лечения", class: "Магический посох", spalls: [spalls.electricDischarge1, spalls.healingSwing1, spalls.lifeEnhancement1], charge: 5, price: 300},
    basicFireStaff: {name: "Базовый посох огня", class: "Магический посох", spalls: [spalls.fieryWhip1, spalls.fireStorm1], charge: 5, price: 300},
    basicVampirStaff: {name: "Базовый посох вампира", class: "Магический посох", spalls: [spalls.bloodyBite1, spalls.witheringSwarm1], charge: 5, price: 300},
    basicPoisonedStaff: {name: "Базовый посох яда", class: "Магический посох", spalls: [spalls.poisonousSpray1, spalls.toxicCloud1], charge: 5, price: 300},
    basicProtectionStaff: {name: "Базовый посох защиты", class: "Магический посох", spalls: [spalls.magicalResistance, spalls.magicPlates1], charge: 5, price: 300},
    basicTactiсStaff: {name: "Базовый посох тактики", class: "Магический посох", spalls: [spalls.tacticalBreakthrough1, spalls.electricDischarge1, spalls.magicPlates1], charge: 5, price: 300},
    basicCharacteristictStaff: {name: "Базовый посох характеристик", class: "Магический посох", spalls: [spalls.increaseStrength1, spalls.increaseDexterity1, spalls.increasePhysique1, spalls.increaseIntelligence1, spalls.increaseWisdom1, spalls.increaseCharisma1], charge: 5, price: 300},
    basicAttackStaff: {name: "Базовый посох Атаки", class: "Магический посох", spalls: [spalls.attackBoost1, spalls.damageBoost1], charge: 5, price: 300},

    сustomizedMagicStaff: {name: "Настроенный посох магии", class: "Магический посох", spalls: [spalls.electricDischarge2, spalls.magicPlates2, spalls.healingSwing2, spalls.massLightning1], charge: 10, price: 3000},
    customizedHealStaff: {name: "Настроенный посох лечения", class: "Магический посох", spalls: [spalls.electricDischarge2, spalls.healingSwing2, spalls.lifeEnhancement2, spalls.magicPlates1], charge: 10, price: 3000},
    customizedFireStaff: {name: "Настроенный посох огня", class: "Магический посох", spalls: [spalls.fieryWhip2, spalls.fireStorm2, spalls.magicPlates1], charge: 10, price: 3000},
    customizedVampirStaff: {name: "Настроенный посох вампира", class: "Магический посох", spalls: [spalls.bloodyBite2, spalls.witheringSwarm2, spalls.attackBoost1], charge: 10, price: 3000},
    customizedPoisonedStaff: {name: "Настроенный посох яда", class: "Магический посох", spalls: [spalls.poisonousSpray2, spalls.toxicCloud2, spalls.healingSwing1], charge: 10, price: 3000},
    customizedProtectionStaff: {name: "Настроенный посох защиты", class: "Магический посох", spalls: [spalls.magicalResistance, spalls.magicPlates2, spalls.healingSwing1], charge: 10, price: 3000},
    customizedTactiсStaff: {name: "Настроенный посох тактики", class: "Магический посох", spalls: [spalls.tacticalBreakthrough2, spalls.electricDischarge2, spalls.magicPlates2, spalls.damageBoost1], charge: 10, price: 3000},
    customizedCharacteristictStaff: {name: "Настроенный посох характеристик", class: "Магический посох", spalls: [spalls.increaseStrength2, spalls.increaseDexterity2, spalls.increasePhysique2, spalls.increaseIntelligence2, spalls.increaseWisdom2, spalls.increaseCharisma2], charge: 10, price: 3000},
    customizedAttackStaff: {name: "Настроенный посох Атаки", class: "Магический посох", spalls: [ПРОПИСАТЬ!!!], charge: 10, price: 3000},

    higherMagicStaff: {name: "Высший посох магии", class: "Магический посох", spalls: [ПРОПИСАТЬ!!!], charge: 15, price: 6000},
    higherHealStaff: {name: "Высший посох лечения", class: "Магический посох", spalls: [ПРОПИСАТЬ!!!], charge: 15, price: 6000},
    higherFireStaff: {name: "Высший посох огня", class: "Магический посох", spalls: [ПРОПИСАТЬ!!!], charge: 15, price: 6000},
    higherVampirStaff: {name: "Высший посох вампира", class: "Магический посох", spalls: [ПРОПИСАТЬ!!!], charge: 15, price: 6000},
    higherPoisonedStaff: {name: "Высший посох яда", class: "Магический посох", spalls: [ПРОПИСАТЬ!!!], charge: 15, price: 6000},
    higherProtectionStaff: {name: "Высший посох защиты", class: "Магический посох", spalls: [ПРОПИСАТЬ!!!], charge: 15, price: 6000},
    higherTactiсStaff: {name: "Высший посох тактики", class: "Магический посох", spalls: [ПРОПИСАТЬ!!!], charge: 15, price: 6000},
    higherCharacteristictStaff: {name: "Высший посох характеристик", class: "Магический посох", spalls: [ПРОПИСАТЬ!!!], charge: 15, price: 6000},
    higherAttackStaff: {name: "Высший посох Атаки", class: "Магический посох", spalls: [ПРОПИСАТЬ!!!], charge: 15, price: 6000}
}


export const artifacts = {
    protectionRing: {name: "Кольцо защиты", class: "Артефакт", effect: 1, target: "ac", price: 6000},
    amuletDrunkard: {name: "Амулет пьяницы", class: "Артефакт способностей", Пр!описат!ь, price: 6000},
    amuletHits: {name: "Амулет здоровья", class: "Артефакт", effect: 1, target: "hits", price: 6000},
    sharpHairpin: {name: "шипастая заколка", class: "Артефакт способностей", Пр!описат!ь, price: 6000},
    handcuffStrenght: {name: "Наруч силы", class: "Артефакт", effect: 1, target: "strenght", price: 6000},
    stylusDexterity: {name: "Перо ловкости", class: "Артефакт", effect: 1, target: "dexterity", price: 6000},
    stonePhysique: {name: "Камень выносливости", class: "Артефакт", effect: 1, target: "physique", price: 6000},
    bookmarkIntelligence: {name: "Книжная закладка интеллекта", class: "Артефакт", effect: 1, target: "intelligence", price: 6000},
    lensWisdom: {name: "Линза мудрости", class: "Артефакт", effect: 1, target: "wisdom", price: 6000},
    flowerCharisma: {name: "Цветок харизмы", class: "Артефакт", effect: 1, target: "charisma", price: 6000},
    ultraGem: {name: "Ультра самоцвет", class: "Мега-артефакт", effect: 1, price: 6000},
    tacticCrystal: {name: "Тактический кристалл", class: "Артефакт характеристик", effect: 1, price: 6000}
}